name: ndocs
description: "N-Docs - Nigerian Document Verification App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0

  # Authentication & Security
  jwt_decoder: ^2.0.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

  # File Handling
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  # Navigation
  go_router: ^14.6.1

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # JSON & Serialization
  json_annotation: ^4.9.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5

  # Additional utilities
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts - Using Google Fonts for Inter font family
